- name: Initialize the cluster
  block:
    - name: Check if cluster had been initialized
      shell: "docker info --format {{ '{{.Swarm.ControlAvailable}}' }} "
      register: swarm_mode
      when: master_node in ansible_all_ipv4_addresses

    - name: Initialize when master is standalone
      shell: docker swarm init --advertise-addr {{ master_node }}
      when: swarm_mode.stdout == "false" and master_node in ansible_all_ipv4_addresses
    
    - name: Get worker join token when master is available
      shell: docker swarm join-token worker
      register: worker_join_command_raw
      when: master_node in ansible_all_ipv4_addresses